name: lint, build, test and deploy

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  lint_compile_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install pnpm
        run: npm install -g pnpm

      - name: install nodes 20
        uses: actions/setup-node@v2
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint
      
      - name: compile
        run: pnpm run compile

      - name: test
        run: pnpm run test

  deploy:
    runs-on: ubuntu-latest
    needs: lint_compile_test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This action deploys to Heroku
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }} 
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
        env:
            CORS_URLS: ${{ env.CORS_URLS }}
        


      