name: lint, build, test and deploy

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  lint_compile_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install nodes 20
        uses: actions/setup-node@v2
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm ci

      - name: Lint
        run: pnpm run lint
      
      - name: compile
        run: pnpm run compile

      - name: test
        run: pnpm run test

  deploy:
    runs-on: ubuntu-latest
    needs: lint_compile_test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh
        
      - name: Login to Heroku
        run: heroku login -i
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Deploy to Heroku
        run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/backend-app-quizz.git HEAD:main

      